"""added withdrawal

Revision ID: 587a26fac6c1
Revises: 203f1f832790
Create Date: 2025-01-31 13:16:23.715798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587a26fac6c1'
down_revision = '203f1f832790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
